### ISSUE TITLE
Community charts suggestion: All the *arr’s!!

### ISSUE THREAD

**Issue by AActionman** [truenas/charts#1094]
radarr, sonarr, lidarr, reader, Prowlarr, overwatcherr!

**Comment by Emalton** [comment]
Overseerr, Bazarr, and Tautulli would be great additions as well that fit with the media apps!

**Comment by Celeths** [comment]
Just a few more to go! Excited to use an official Prowlarr release one day.

**Comment by cubix-netizen** [comment]
autobrr would be awesome, just my two cents 😄

**Comment by stavros-k** [comment]
Making a list to keep track of those and I'll update it on the way 🚀 

- [x] radarr (#1089)
- [x] sonarr (#1082)
- [x] lidarr (#1100)
- [x] overseerr (#1170)
- [ ] readarr
- [ ] prowlarr
- [ ] overwatcher
- [ ] bazarr
- [ ] plex auto lanuages
- [ ] recyclarr
- [ ] tautulli
- [ ] autobrr

**Comment by pavleknezevic** [comment]
Can you add homarr to the list?

**Comment by stavros-k** [comment]
> radarr, sonarr, lidarr, reader, Prowlarr, overwatcherr!

Can you share a link for overwatcherr? I can't find it.
Thanks

**Comment by CompPhy** [comment]
Is there any plan for regular updates to these apps?  I'm finally trying to move away from TrueCharts, only to find out that that I'm going to have to downgrade some on my apps because they aren't up to date here.

For example, Lidarr app says version 1.1.3.2982 is "Up To Date" but in fact is a 6 month old "pre-release" version that isn't even considered stable upstream.  Current "stable" version should be 1.2.6.3313, as per here:  https://github.com/Lidarr/Lidarr/releases

I'm interested in contributing here, and will try to work up a PR for some of the apps that are already in the community charts.  However, I do have questions about how to validate changes.  I'm not really familiar with how to help validate my PR before submitting the change.  Is there a way to attach my own TrueNAS instance to my fork, or something similar?  

Most of the documentation in this repository seems to be around setting up the chart files, and doesn't really indicate how to contribute and validate changes within the repository.  Maybe I'm just looking the wrong place for the documentation on how to contribute?

**Comment by stavros-k** [comment]
> Is there any plan for regular updates to these apps? I'm finally trying to move away from TrueCharts, only to find out that that I'm going to have to downgrade some on my apps because they aren't up to date here.
> 
> For example, Lidarr app says version 1.1.3.2982 is "Up To Date" but in fact is a 6 month old "pre-release" version that isn't even considered stable upstream. Current "stable" version should be 1.2.6.3313, as per here: https://github.com/Lidarr/Lidarr/releases

Looks like the issue here is simillar to this https://github.com/truenas/charts/pull/1347 
Will look into it shortly.

> I'm interested in contributing here, and will try to work up a PR for some of the apps that are already in the community charts. However, I do have questions about how to validate changes. I'm not really familiar with how to help validate my PR before submitting the change. Is there a way to attach my own TrueNAS instance to my fork, or something similar?

You can add additional catalogs in Apps > Manage Catalog section on your server

> Most of the documentation in this repository seems to be around setting up the chart files, and doesn't really indicate how to contribute and validate changes within the repository. Maybe I'm just looking the wrong place for the documentation on how to contribute?

Currently there isn't a straightforward way test on TN SCALE while developing.
I usually make sure the helm chart works locally on a bootstrapped k3s cluster, and then create a dummy catalog add it on a test TN SCALE system and do few more checks there like questions.yaml is rendered correctly, installation, upgrade etc.

**Comment by AActionman** [comment]
thanks Pavleknezevic, you're correct. I did mean Overseerr. @stavros-k thank you so much for everything you've done with this train of apps so far, I'm truly grateful, and I'm sure many others are too

**Comment by CompPhy** [comment]
I will second that, thank you @stavros-k.  And thank you for taking the time to answer my questions about future contributions.

**Comment by MK00000000000000000000** [comment]
Awesome work! I would love to see homepage and tiny media manager (tmm) added!

**Comment by kmoore134** [comment]
Congrats getting this done!
