### ISSUE TITLE
Tailscale doesn't create a network interface

### ISSUE THREAD

**Issue by gravelfreeman** [truenas/charts#1734]
When checking Host Networking, the network interface under Network, isn't created.

This is problematic since I can't access Kubernetes apps from tailscaleip:port.

I can only access the webui of TrueNAS from the Tailscale IP.

Same behaviour tested on 2x different TrueNAS Scale Cobia servers. Also many users online are reporting the same issue.

Also I was wondering if I had to setup those Sysctl variables in Advanced?

- `net.ipv4.ip_forward`
- `net.ipv4.conf.all.src_valid_mark`

https://github.com/truenas/charts/tree/master/community/tailscale

**Comment by bcat** [comment]
Having recently gone down this path myself:

1. Are you sure the interface isn't being created, or is TrueNAS just not _displaying_ it? If you SSH in and run `ip link`, do you see a `tailscale0` interface? I do (with both the TrueNAS official chart and the TrueCharts chart).

2. I _think_ the issue may not be with TrueNAS, but rather with k3s (and/or the way TrueNAS has it set up... I'm really not sure). From what I've read in various places online, the TrueNAS Kubernetes apps will only egress out one interface. This leads to weirdness like traffic from apps to the LAN hitting the DHCP-provided default gateway (for no particular reason). I think it _also_ means that although traffic from the Tailscale interface might reach the k3s apps, response packets from the apps are never routed _back_ through the k3s interface.

Honestly, this is a bit frustrating, and another reason I'm considering just moving my hosted services to Docker containers in a VM. :) But maybe this will provide a jumping-off point for someone who actually understand Kubernetes (which I certainly don't) to dig deeper?

**Comment by gravelfreeman** [comment]
You're right I just tried `ip link` and it returned the following interface

```
18: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 500    link/none
```

Is there a way to force the interface to show up under Network?

It's a remote server and I don't need local access to my apps at all. I would like to expose the Kubernetes network on the node ip which would be the tailscale ip. Thing is that I can't choose it from that dropdown because the interface isn't showing here

![image](https://github.com/truenas/charts/assets/44218371/c15ec3da-756b-4d56-89a9-a2fb7c203bf4)

Someone on TrueNAS Discord said that it's normal the interface isn't created since the chart doesn't run as an elevated user. I can't change the PUID and GUID to root on the official chart, might be able on the truecharts one though.

I've seen Lawrence on Youtube (video is 2 months old), being able to create the tailscale0 interface with the official chart.

Cobia really did f*ed everything up.

**Comment by bcat** [comment]
Huh, interesting. That wouldn't work for me (as I need access to services via both LAN and Tailscale), but otherwise, configuring Kubernetes to use the Tailscale IP for the node IP might work (at the cost access to apps on other interfaces)... if the TrueNAS middleware were aware of that interface. :)

But also, I'm not sure how the timing would work. Presumably the interface has to exist for apps to start up, but `tailscale0` doesn't exist before the Tailscale app is started. I wouldn't necessarily expect to be able to configure Kubernetes to use the interface that a Kubernetes app itself is responsible for the creation of.

Side note: It's subject to break on future TrueNAS upgrades, and I've not yet tested it myself... but I've been looking into moving apps into systemd-nspawn containers managed via the [Jailmaker](https://github.com/Jip-Hop/jailmaker) script. It's reasonably self contained, and seems like a way to keep the advantages of running containers on the host (direct dataset access, easy access to host hardware) with fewer constraints than the apps ecosystem imposes. So if you nonstandard requirements, this may be worth a look.

**Comment by gravelfreeman** [comment]
I can't find it anymore but someone posted on the forum and said he was able to access his apps with Tailscale only and not his local IP anymore. I didn't say more than he set DHCP off, set static IP and chose tailscale0 ip as the node ip in advanced config. I want to do this but the network interface isn't in the gui.

Please someone help me!

**Comment by gravelfreeman** [comment]
So there's no need to add it as an interface. I got it to work by adding the Tailscale IP to my nic

![image](https://github.com/truenas/charts/assets/44218371/1d307bb5-6780-46c3-b8e4-d2bf150524a9)

Then only in the Truecharts version of Tailscale I've been able to choose my nic.

![image](https://github.com/truenas/charts/assets/44218371/884a68af-b2c6-4109-ac5d-7d7ac1011566)

Alhough I'm not sure this is step is necessary. To be frank I don't really understand how the network is working but this worked.

I'm able to choose the Tailscale IP in advanced kubernetes settings.

![image](https://github.com/truenas/charts/assets/44218371/3457e569-7b3c-4ca8-b513-db8dc475331e)

With this setup I'm able to access all of the remote apps by using TAILSCALEIP:APPPORT

I quickly figured out it was useless since I would have to do the same on my main local server and this would mean I'd be loosing access to my apps locally and always connect to them with the tailscale IP. I'm not sure that's a good thing...

I tried using 0.0.0.0 as the node IP but the app would only be accessible with LOCALIP:APPPORT and not by the tailscale IP. I read somewhere it could be done but that it's complicated and by default kube doesn't support 2x nodes IPs.

If you have any ideas of what would be the advanced technique to make my apps accessible from both my local and tailscale IP it would solve all of my issues!

Thanks for helping!

**Comment by gravelfreeman** [comment]
So I've been able to setup access to my apps using reverse proxy with Traefik and blocky. Unfortunately apps that doesn't work with ingress can't be access by tailscaleip:port.

You need to setup everything (traefik/blocky/cert-manager) as per Truecharts documentation and then install your preferred Tailscale chart. I find the one from the official catalog to be easier albeit less customization.

Tailscale options are

![image](https://github.com/truenas/charts/assets/44218371/3bc97938-5667-44f6-a9d2-94d84c366864)

![image](https://github.com/truenas/charts/assets/44218371/9bfce7b9-e604-4c61-bcd9-575e5c6ab2e9)

Now go to tailscale.com >Admin > DNS > Nameservers, and set the following:

Add your preferred public DNS service (my preference is Cloudflare)

Add a custom DNS service with your server's local IP and your clusterissuer domain

![image](https://github.com/truenas/charts/assets/44218371/68641e31-38a2-4614-8f6b-5c8ddb6ccb98)

You want to check the Override local DNS box (important).

It should look like this in the end:

![image](https://github.com/truenas/charts/assets/44218371/3d27aadf-5faa-46da-b22c-b8cd2a1968a9)

Now you can access all your ingress apps using any client on your Tailscale network.

Next step for me is to get kubernetes apps from server A talks to apps on server B.

**Comment by stavros-k** [comment]
I'm going to close this firstly because as @bcat mentioned, even if this somehow worked, it would definitely cause a chicken and egg scenario, where k8s try to use an interface that does not exist and will fail to start, and the interface will not exist unless k8s start.

Furthermore, looks like this becoming more of a TrueCharts walkthrough/guide/how-to.
Which is something that I'd suggest sharing with them.

Thanks!

**Comment by gravelfreeman** [comment]
Completely agree, thanks!
