### ISSUE TITLE
Let Us Tinker

### ISSUE THREAD

**Issue by PurplePumkiin** [truenas/charts#1957]
I understand the push towards a more commercial and enterprise ready product, but its getting kinda dumb now. Ive been using SCALE for a couple years because of the docker capabilities, but with every major release I find more and more control being taken from me. APT is taken from us, so the burden of installing some basic packages has kinda fallen on the devs. For instance, my entire issue revolves around not having PHP for nextcloud. The entire point of scale is to be on the edge, and sometimes you need to do funky things to data on said edge, give us our coding libraries, or integrate a custom package manager so we can install some cherry picked packages. I don't want to modify scale to much, but from what I understand that's the route I need to take.

Also please stop with the GUI's, they're nice for some things, but I've had to move away from scale for my more niche docker containers now, I don't get the same configurability from a static GUI page and Cobia removed docker so I had to move away.

**Comment by stavros-k** [comment]
Even if the APT was available, it wouldnt solve the PHP modules for nextcloud. (See also #1868)
Nextcloud runs in container(s) (as all the apps), and the modules need to be installed there.
We consume the official Nextcloud container, so I'd suggest to ask them to include the PHP modules you need.

For your "niche" or custom containers, there is a `Custom App` blue button on the Apps page that you can try.

Unfortunately this is the only thing I can comment on here, as this is the only Charts related mention.

**Comment by PurplePumkiin** [comment]
But you see, next cloud does have its own PHP modules, the problem is it lacks cron scheduling, and to be frank I'd rather that cron be handled by the host not the container, for my use case at least, it feels more comfortable for the data handling I do. So I disagree, PHP should be in scale, not only the container.

**Comment by PurplePumkiin** [comment]
Ill admit that I know very little about the inner workings of scale and its systems, but why couldn't we have PHP built in. What does it really hurt, people can already screw their OS up easy enough so its not like it poses a risk to the user?

**Comment by stavros-k** [comment]
I'm not the person that can officially answer those questions, as it's not my area. This repo is about Charts/Apps and not the host system.

**Comment by kmoore134** [comment]
To be clear, this repo is for the Apps specifically, not the overall ability to "tinker" on TrueNAS. Those two things are often in conflict, many Apps users just want to click a few things and have it work, whereas others wants to fiddle with all the knobs under the hood. 

We are working to lock down the base appliance OS, so that there is less overall foot-shooting and security risks out of box on TrueNAS, but we also understand the need for folks to have a proper "Sandbox" to fully tinker and setup non-standard things. In Dragonfish (24.04) we'll be adding the ability to setup manual Linux Sandboxes, so that the tinkers have more complete control and can run "apt" and friends to their hearts content to setup custom services. This will be using systemd-nspawn and is in the nightly images now as a CLI-only thing, but the idea is you can make your own sandbox/jail/chroot on steroids and tinker as much as you like, without running the risk of breaking various core NAS functionality.

**Comment by kmoore134** [comment]
Closing this out. We will have some of this capability landing in 24.04-BETA.1 in a few weeks:

https://github.com/truenas/documentation/pull/2445
