### ISSUE TITLE
homepage does not set Host Path permissions correctly

### ISSUE THREAD

**Issue by CompPhy** [truenas/charts#1961]
Name: homepage
App Version: 0.8.3
Chart Version: 1.2.0

The homepage app doesn't set permissions properly on fresh install, when using Host Path storage.  This causes it to fail creating any configuration file.  Error after startup:  Error: EACCES: permission denied, copyfile '/app/src/skeleton/settings.yaml' -> '/app/config/settings.yaml'

I have not tested with ixVolume, it's possible this works fine.  For my setup I prefer Host Path, and was able to get it working with the workaround listed below.

I may be off base here, but I think there's two issues.  
1) There does not appear to be an initcontainer to set permissions on the storage before the main application starts.
2) The container uses UID 1000, instead of 568, so even if you set the storage to "app" user manually, it still gets permissions errors.

As a workaround, I had to manually set UID and GID to 1000 on the storage.  This let's the application write proper config files and function normally.

**Comment by stavros-k** [comment]
Hello, this works as expected. we only perform permission changes on newly created ixVolumes.
HostPaths are managed exclusively by you. You can however use the ACLs to set permissions right from the Apps UI. (Assuming you are on Cobia release)

And thats correct, the app users UID 1000, currently does not seem that we can allow this to be configurable due to upstream issues.
