### ISSUE TITLE
Home Assistant - automations.yaml not linked from the configuration.yaml

### ISSUE THREAD

**Issue by EpicFail113** [truenas/charts#2728]
When you install Home Assistant and try to create any automatons it allows you to go through the whole process and even lets you test the automation but it does not actually save.

There is also nowhere in the UI that lets you change the configuration.yaml

**Comment by InfiniteBed** [comment]
**There's two parts to this comment. The first section pertains to actually fixing your problem, and the second is my advice to you.**

If external volumes have been set, then this most likely pertains to a permission issue. Home Assistant may not have appropriate permission to save the automation to the file. Go to the TrueNAS shell, `cd` into the directory of your Home Assistant data directory `sudo chown 568 -Rv`. This should give ownership of the files to Home Assistant, and allow it to save to disk.

configuration.yaml is not something that can be easily edited inside of Home Assistant. To edit configuration.yaml, add-ons like File Browser or Visual Studio Code Server must be installed, which is not as simple with the TrueNAS application.

**Now for my personal recommendation.**

As I understand it, TrueNAS's application uses the "Container" version of the Home Assistant install (refer to [this chart](https://www.home-assistant.io/installation/#advanced-installation-methods) and [this visualization](https://media.discordapp.net/attachments/332167321311510530/875109800839630878/unknown.png?ex=66d4cb03&is=66d37983&hm=2ca7a7c1a00dca65cd2ada5eec7ba5ac9692bb346a1d392a27a8dbd1eb273672&=&format=webp&quality=lossless&width=2268&height=878) to understand more about install methods). For ease of use, I would highly recommend following [this method](https://community.home-assistant.io/t/installing-haos-in-a-vm-on-truenas-scale/511393) to install Home Assistant. It takes a bit of troubleshooting and understanding to follow through, but once it is complete, it will run flawlessly.

**Comment by adavis0331** [comment]
From my understanding, there are defaults in the configurations.yaml file that should be part of an initial installation.  Namely:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

I also had to add a blank "scripts.yaml" and "scenes.yaml" since they weren't there. My automations were all actually saved but the way it's initially setup, Home Assistant wasn't pulling anything from the file.  With the changes, everything works as it should.  This could be added to initial setup right? The thread below goes into it in more detail.

https://community.home-assistant.io/t/automations-not-saving/155921/24
