### ISSUE TITLE
Minecraft: Webserver-based plugins unusable; Suggestion to add config option for webserver-based plugins.

### ISSUE THREAD

**Issue by false-fox** [truenas/charts#2764]
Trunas Scale does not allow the ability to open custom ports on the docker container for applications.

This is a bit troubling for server owners such as myself who want to use server plugins that rely on webservers (for example: [dynmap](https://modrinth.com/plugin/dynmap) or [bluemap](https://bluemap.bluecolored.de/), both provide a web-based interactive map of the world), which host themselves on the local ports 8100 and 8123 respectively.

There is (seemingly) no current way to open ports 8100 and 8123 on the container to free them, unless the maintainer deliberately adds functionality to open ports.

an option in the networking section to open an arbitrary port range for HTTP/HTTPS apps would solve this. Thank you :)

**Comment by Bloodis94** [comment]
I think you might want to wait for electric eel to roll out in Q4. At the moment the apps on SCALE are just Helm Charts used to orchestrate a Kubernetes cluster so i think it would be difficult to achieve your objective without a custome chart or atleaste some shell workaround.

In electric eel from what i've read they will migrate to docker + docker compose since a lot of people have needs similar to yours.

**Comment by stavros-k** [comment]
Yes, such changes would be targeted for the docker backend apps, so it will not complicate migrations.
Thanks!
