### ISSUE TITLE
Immich version is older than 1 month.

### ISSUE THREAD

**Issue by vismay1003** [truenas/charts#2964]
Hi Immich is not on current version and looks like 2 version behind. I'm a regular Immich user and wanted to know if I can help keep this chart up to date. 

I will need some guidance though. I haven't done this in past.

Regards,
Vismay

**Comment by stavros-k** [comment]
Charts that require changes to work, like Immich in this case, will not be updated for Dragonfish.
As it will break migration path to Electric Eel.

You can upgrade to electric eel that has Immich updated.

**Comment by tjhorner** [comment]
This is pretty disappointing to see since I am staying on Dragonfish for the time being, as EE has some breaking changes that prevents me from upgrading directly (see [this forum post](https://forums.truenas.com/t/inter-app-communication-in-24-10-electric-eel/22054)).

I am not opposed to maintaining my own charts repository, but it's sort of unclear to me where to start and — crucially — how to make sure the volumes migrate over to the new chart without interruption. Would appreciate some links to resources if those are available.

**Comment by vismay1003** [comment]
@tjhorner , not sure about the other problems that you mentioned but, in terms for volumes I didn't have to do anything when I upgraded to EE.
Everything is working fine for me as of now.

**Comment by tjhorner** [comment]
@vismay1003 I have no concern with volumes migrating from Dragonfish to EE. The concern is migrating volumes from a deployment based on the official TrueNAS chart to a forked one (i.e., still on Dragonfish)
